In [62]:
import pandas as pd
import matplotlib.pyplot as plt
import os

os.getcwd()

'/Users/chenxinhe/26winter/capstone'

In [63]:
pd.read_csv('Envision Resilience Challenge Engagement and Network Mapping Survey (Responses without phases) - Form Responses 1.csv')

,Timestamp,Email Address,What is your name?,What was your role in this challenge?,Please select which phase(s) you were most active in:,Please select your year(s) of involvement (check all that apply):,"Were you involved in the 2021 Envision Resilience Challenge (ERC) in Nantucket, Massachusetts?",Approximately how many community participants or partners did you involve in planning this challenge?,Which methods did you use to engage with the local stakeholders?,"For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:",...,Approximately how many community participants or partners did you involve in planning this challenge?.4,Which methods did you use to engage with the local stakeholders?.4,"For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:.4","Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.4",Which types of key advisors were most influential in shaping this challenge? Select up to three. .4,Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?.4,In which of the following areas do you think ERC has had the strongest community influence? (Select up to two),How do you personally define “impact” in the context of the Envision Resilience Challenge? (This helps us understand how participants conceptualize success and influence.),"Are there examples of lasting effects from any challenge you’ve participated in (such as continued partnerships, implemented projects, curriculum changes, or new community initiatives?) If so, please describe them.\n",Any additional comments or reflections about engagement or networking during your ERC experience?
0,11/4/2025 10:43:49,cxinhe@umich.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11/4/2025 12:19:36,yunjiazo@umich.edu,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11/14/2025 16:11:00,cvanvoorhis@envisionresilience.org,Charlotte Van Voorhis,ERC program organizer,"Pre-challenge (planning and set-up), Post-chal...","2023 (New Bedford & Fairhaven, Massachusetts),...",No,NaN,NaN,NaN,...,75,"Regular meetings, Workshops, Informal discussions","Rod Melanson - supportive, conscientious, welc...","Gayle Bowness, Rod Melanson, Debora Keller, Ja...","Nonprofit organizations, Municipal or governme...","Sean Ireland, Paul Plummer, Mandy Reynolds, Do...","Design innovation, Policy influence",Community members who feel hopeful after worki...,We continue to have partnerships in New Bedfor...,NaN
3,11/17/2025 11:15:31,cjensen@remain.org,Cecil,staff/strategic advisor,"Pre-challenge (planning and set-up), Challenge...","2021 (Nantucket, Massachusetts), 2022 (Narraga...",Yes,25-30 people,"Regular meetings, Shared digital tools (like M...","Robert Miklos, Marty Hilton, Harrison Fraker",...,NaN,NaN,NaN,NaN,NaN,NaN,"Community empowerment, Public awareness",Permanently changing people's -- seeing the fu...,Yes! Community education impact in Nantucket a...,The interconnection between study areas is pow...
4,11/17/2025 11:24:16,kdeans@envisionresilience.org,Kate Deans,ERC program organizer,"Pre-challenge (planning and set-up), Challenge...",2025 (Midcoast Maine),No,NaN,NaN,NaN,...,My role does not directly interface with the c...,NaN,NaN,NaN,NaN,NaN,"Education, Community empowerment","To me, it is about an ability to comprehend an...",NaN,NaN
5,11/23/2025 17:26:01,ccox.advisor@envisionresilience.org,Carolyn Cox,ERC program organizer,"Pre-challenge (planning and set-up), Challenge...","2021 (Nantucket, Massachusetts), 2022 (Narraga...",Yes,50,Informal discussions,"Cecil Barron Jenson, funder, nonprofit, connec...",...,30,"Regular meetings, Informal discussions","Rod Melanson, sustainability, connector\nHolly...",Rod Melanson,"Municipal or government staff, Technical or sc...",ER staff and advisors,Design innovation,Helps community see future potential,too numerous,NaN
6,11/25/2025 13:55:34,cmartin@envisionresilience.org,Claire Martin,ERC program organizer,"Pre-challenge (planning and set-up), Challenge...","2021 (Nantucket, Massachusetts), 2022 (Narraga...",Yes,"~15-25, with ~10 core partners","Regular meetings, Shared digital tools (like M...","Mary Bergman - historian, community-centric, i...",...,20-30,"Regular meetings, Shared digital tools (like M...","Rod Melanson - innovator, connector, forward-t...",NaN,"Municipal or government staff, Technical or sc...",NaN,"Education, Public awareness","In the context of ERC, impact is about our abi...","1. New Bedford, Massachusett's Riverside Park ...",We are a very self-reflective organization. Ea...
7,11/25/2025 16:03:53,sakufo@envisionresilience.org,Sandra Akufo,Student Participant in the 2023 New Bedford Ch...,"Pre-challenge (planning and set-up), Challenge...","2023 (New Bedford & Fairhaven, Massachusetts),...",No,NaN,NaN,NaN,...,I mainly write challenge briefs before the stu...,Informal discussions,Curtis Bohlen (Only collaborator that I met); ...,Curtis Bohlen has been an advisor in the 2024 ...,"Nonprofit organizations, Municipal or governme...",NaN,"Education, Community empowerment",Impact in ERC - The implementation of student ...,New Bedford Challenge -- student mural for ERC...,NaN
8,11/26/2025 11:14:54,wjoseph@envisionresilience.org,Wendell T. Joseph,ERC program organizer,Challenge (design and engagement period),2025 (Midcoast Maine),No,NaN,NaN,NaN,...,NaN,Regular meetings,NaN,NaN,NaN,NaN,"Education, Community empowerment, Public aware...","I would define ""impact"" as 'the extent to whi...",NaN,I never get tired of seeing how people we're c...
9,12/3/2025 11:22:08,rjmiklos@gmail.com,Robert Miklos FAIA,Academic Advisor for the ERC program,"Pre-challenge (planning and set-up), Challenge...","2021 (Nantucket, Massachusetts), 2022 (Narraga...",Yes,50 or more,"Workshops, Informal discussions","Chuck Larson, Jennifer Karberg, Emily Molden",...,25,"Regular meetings, Co-design sessions, Workshop...","Rod Melanson, Jamie Hark, Jenn Curtis","Rod Melanson, Curtis Bohlen, Jamie Hark","Nonprofit organizations, Municipal or governme...",Sean Ireland,"Education, Design innovation, Public awareness",broadening awareness of climate risks but also...,"Several -Town Warren, New Bedford Parks, Portl...",Need to reach larger community participation-...

In [64]:
df = pd.read_csv('Envision Resilience Challenge Engagement and Network Mapping Survey (Responses without phases) - Form Responses 1.csv')
df.columns

Index(['Timestamp', 'Email Address', 'What is your name?',
       'What was your role in this challenge?',
       'Please select which phase(s) you were most active in:',
       'Please select your year(s) of involvement (check all that apply):',
       'Were you involved in the 2021 Envision Resilience Challenge (ERC) in Nantucket, Massachusetts?',
       'Approximately how many community participants or partners did you involve in planning this challenge?',
       'Which methods did you use to engage with the local stakeholders?',
       'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:',
       'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?',
       'Which types of key advisors were most influential in shaping this challenge? Select up to three. ',
       'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?',
       'Were you involved in the 2022 Envision Resilience Challenge (ERC) in Narragansett Bay, Rhode Island?',
       'Approximately how many community participants or partners did you involve in planning this challenge?.1',
       'Which methods did you use to engage with the local stakeholders?.1',
       'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:.1',
       'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.1',
       'Which types of key advisors were most influential in shaping this challenge? Select up to three. .1',
       'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?.1',
       'Were you involved in the 2023 Envision Resilience Challenge (ERC) in New Bedford & Fairhaven, Massachusetts?',
       'Approximately how many community participants or partners did you involve in planning this challenge?.2',
       'Which methods did you use to engage with the local stakeholders?.2',
       'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:.2',
       'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.2',
       'Which types of key advisors were most influential in shaping this challenge? Select up to three. .2',
       'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?.2',
       'Were you involved in the 2024 Envision Resilience Challenge (ERC) in Portland & South Portland, Maine?',
       'Approximately how many community participants or partners did you involve in planning this challenge?.3',
       'Which methods did you use to engage with the local stakeholders?.3',
       'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:.3',
       'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.3',
       'Which types of key advisors were most influential in shaping this challenge? Select up to three. .3',
       'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?.3',
       'Were you involved in the 2025 Envision Resilience Challenge (ERC) in Midcoast Maine?',
       'Approximately how many community participants or partners did you involve in planning this challenge?.4',
       'Which methods did you use to engage with the local stakeholders?.4',
       'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:.4',
       'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.4',
       'Which types of key advisors were most influential in shaping this challenge? Select up to three. .4',
       'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?.4',
       'In which of the following areas do you think ERC has had the strongest community influence? (Select up to two)',
       'How do you personally define “impact” in the context of the Envision Resilience Challenge? (This helps us understand how participants conceptualize success and influence.)',
       'Are there examples of lasting effects from any challenge you’ve participated in (such as continued partnerships, implemented projects, curriculum changes, or new community initiatives?) If so, please describe them.\n',
       'Any additional comments or reflections about engagement or networking during your ERC experience?'],
      dtype='str')

In [65]:
#Drop the first two rows which are nodata
df = df.iloc[2:].reset_index(drop=True)

In [66]:
raw_df = df.copy()
df = raw_df.copy()

#Extract the name and role columns for each respodent
analysis_df_id = df[[
    'What is your name?',
    'What was your role in this challenge?',
]]

analysis_df_id = analysis_df_id.rename(columns={
    "What is your name?": "name",
    "What was your role in this challenge?": "role",
})
print("analysis_df_id:")
print(analysis_df_id.head())
analysis_df_id.shape

analysis_df_id:
                    name                     role
0  Charlotte Van Voorhis    ERC program organizer
1                 Cecil   staff/strategic advisor
2             Kate Deans    ERC program organizer
3            Carolyn Cox    ERC program organizer
4          Claire Martin    ERC program organizer

(8, 2)

In [67]:
#Extract the participated duration
analysis_df_duration = df[[
    'Please select your year(s) of involvement (check all that apply):',
]]

analysis_df_duration = analysis_df_duration.rename(columns={
    'Please select your year(s) of involvement (check all that apply):': 'duration'
})
print("analysis_df_duration:")
print(analysis_df_duration.head())
analysis_df_duration.shape

analysis_df_duration:
                                            duration
0  2023 (New Bedford & Fairhaven, Massachusetts),...
1  2021 (Nantucket, Massachusetts), 2022 (Narraga...
2                              2025 (Midcoast Maine)
3  2021 (Nantucket, Massachusetts), 2022 (Narraga...
4  2021 (Nantucket, Massachusetts), 2022 (Narraga...

(8, 1)

In [68]:
#Extract the community participation
analysis_df_community = df[[
    'Approximately how many community participants or partners did you involve in planning this challenge?',
    'Which methods did you use to engage with the local stakeholders?',
]]

analysis_df_community = analysis_df_community.rename(columns={
    'Approximately how many community participants or partners did you involve in planning this challenge?': 'community_participants_number',
    'Which methods did you use to engage with the local stakeholders?': 'community_participants_methods',
})
print("analysis_df_community:")
print(analysis_df_community.head())
for col in df.columns:
    if "Approximately how many community participants" in col:
        print(col)
analysis_df_community.shape

analysis_df_community:
    community_participants_number  \
0                             NaN
1                    25-30 people
2                             NaN
3                              50
4  ~15-25, with ~10 core partners

                      community_participants_methods
0                                                NaN
1  Regular meetings, Shared digital tools (like M...
2                                                NaN
3                               Informal discussions
4  Regular meetings, Shared digital tools (like M...
Approximately how many community participants or partners did you involve in planning this challenge?
Approximately how many community participants or partners did you involve in planning this challenge?.1
Approximately how many community participants or partners did you involve in planning this challenge?.2
Approximately how many community participants or partners did you involve in planning this challenge?.3
Approximately how many community participants or partners did you involve in planning this challenge?.4

(8, 2)

In [69]:
#Extract the advisors
analysis_df_advisors = df[[
    'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:',
    'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?',
    'Which types of key advisors were most influential in shaping this challenge? Select up to three. ',
    'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?',
]]

analysis_df_advisors = analysis_df_advisors.rename(columns={
    'For your top three most influential collaborators overall, please list their name and three adjectives that best describe their contribution or role:': 'top3_advisors_list',
    'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?': 'advisors_as_connectors',
    'Which types of key advisors were most influential in shaping this challenge? Select up to three. ': 'inf_advisors_types',
    'Is there anyone not listed who you believe played a significant but less visible role in building or maintaining engagement networks in this challenge?': 'advisors_other'
})
print("analysis_df_advisors:")
print(analysis_df_advisors.head())
analysis_df_advisors.shape

analysis_df_advisors:
                                  top3_advisors_list  \
0                                                NaN
1       Robert Miklos, Marty Hilton, Harrison Fraker
2                                                NaN
3  Cecil Barron Jenson, funder, nonprofit, connec...
4  Mary Bergman - historian, community-centric, i...

                              advisors_as_connectors  \
0                                                NaN
1                        Both connectors and bridges
2                                                NaN
3                           Marty Hylton, Bob Miklos
4  Mary Bergman, Marty Hylton, Cecil Barron Jense...

                                  inf_advisors_types  \
0                                                NaN
1  Nonprofit organizations, Municipal or governme...
2                                                NaN
3  Nonprofit organizations, Technical or scientif...
4  Nonprofit organizations, Technical or scientif...

                                      advisors_other
0                                                NaN
1                                     Anne Dougherty
2                                                NaN
3         Carolyn Cox and Claire Martin did the most
4  Vince Murphy, Tobias Glidden, Niles Parker, Ha...

(8, 4)

## Merge ERC Staff and Duration

In [70]:
#Explode year list
analysis_df_duration["year_list"] = (
    analysis_df_duration["duration"]
    .str.findall(r"\d{4}")
)

analysis_df_duration_long = analysis_df_duration.explode("year_list")

In [71]:
analysis_df_duration_long.shape

(26, 2)

In [72]:
analysis_df_duration_long = analysis_df_duration_long.rename(
    columns={"year_list": "year"}
)

analysis_df_duration_long["year"] = analysis_df_duration_long["year"].astype(int)
analysis_df_duration_long["year"].value_counts().sort_index()

year
2021    4
2022    4
2023    6
2024    5
2025    7
Name: count, dtype: int64

### 参加情况
在我们的调查对象当中，
- 2021年4人参与
- 2022年4人参与
- 2023年6人参与
- 2024年5人参与
- 2025年7人参与

（有个人干啥呢？

In [73]:
analysis_df_duration = analysis_df_duration.reset_index(drop=True)
analysis_df_duration["respondent_id"] = analysis_df_duration.index

In [74]:
analysis_df_duration["year_list"] = analysis_df_duration["duration"].str.findall(r"\d{4}")
analysis_df_duration_long = (
    analysis_df_duration
    .explode("year_list")
    .rename(columns={"year_list": "year"})
    .drop(columns=["duration"])
    .reset_index(drop=True)
)

analysis_df_duration_long["year"] = analysis_df_duration_long["year"].astype(int)

In [75]:
analysis_df_id = analysis_df_id.reset_index(drop=True)
analysis_df_id["respondent_id"] = analysis_df_id.index

In [76]:
analysis_df_duration_long .columns

Index(['year', 'respondent_id'], dtype='str')

In [77]:
analysis_df_duration_long = analysis_df_duration_long.merge(
    analysis_df_id[["respondent_id", "name", "role"]],
    on="respondent_id",
    how="left")
analysis_df_duration_long.columns

Index(['year', 'respondent_id', 'name', 'role'], dtype='str')

In [78]:
analysis_df_duration_long

,year,respondent_id,name,role
0,2023,0,Charlotte Van Voorhis,ERC program organizer
1,2024,0,Charlotte Van Voorhis,ERC program organizer
2,2025,0,Charlotte Van Voorhis,ERC program organizer
3,2021,1,Cecil,staff/strategic advisor
4,2022,1,Cecil,staff/strategic advisor
5,2023,1,Cecil,staff/strategic advisor
6,2024,1,Cecil,staff/strategic advisor
7,2025,2,Kate Deans,ERC program organizer
8,2021,3,Carolyn Cox,ERC program organizer
9,2022,3,Carolyn Cox,ERC program organizer
10,2023,3,Carolyn Cox,ERC program organizer
11,2024,3,Carolyn Cox,ERC program organizer
12,2025,3,Carolyn Cox,ERC program organizer
13,2021,4,Claire Martin,ERC program organizer
14,2022,4,Claire Martin,ERC program organizer
15,2023,4,Claire Martin,ERC program organizer
16,2024,4,Claire Martin,ERC program organizer
17,2025,4,Claire Martin,ERC program organizer
18,2023,5,Sandra Akufo,Student Participant in the 2023 New Bedford Ch...
19,2025,5,Sandra Akufo,Student Participant in the 2023 New Bedford Ch...
20,2025,6,Wendell T. Joseph,ERC program organizer
21,2021,7,Robert Miklos FAIA,Academic Advisor for the ERC program
22,2022,7,Robert Miklos FAIA,Academic Advisor for the ERC program
23,2023,7,Robert Miklos FAIA,Academic Advisor for the ERC program
24,2024,7,Robert Miklos FAIA,Academic Advisor for the ERC program
25,2025,7,Robert Miklos FAIA,Academic Advisor for the ERC program

## Add index to Community

In [79]:
base_col = "Approximately how many community participants or partners did you involve in planning this challenge?"

year_map = {
    base_col: 2021,
    base_col + ".1": 2022,
    base_col + ".2": 2023,
    base_col + ".3": 2024,
    base_col + ".4": 2025,
}

community_cols = list(year_map.keys())
community_cols

['Approximately how many community participants or partners did you involve in planning this challenge?',
 'Approximately how many community participants or partners did you involve in planning this challenge?.1',
 'Approximately how many community participants or partners did you involve in planning this challenge?.2',
 'Approximately how many community participants or partners did you involve in planning this challenge?.3',
 'Approximately how many community participants or partners did you involve in planning this challenge?.4']

In [80]:
missing = [c for c in community_cols if c not in df.columns]
missing

[]

In [81]:
community_wide = df[community_cols].copy()
community_wide = community_wide.reset_index(drop=True)
community_wide["respondent_id"] = community_wide.index

community_wide

,Approximately how many community participants or partners did you involve in planning this challenge?,Approximately how many community participants or partners did you involve in planning this challenge?.1,Approximately how many community participants or partners did you involve in planning this challenge?.2,Approximately how many community participants or partners did you involve in planning this challenge?.3,Approximately how many community participants or partners did you involve in planning this challenge?.4,respondent_id
0,NaN,NaN,100,50,75,0
1,25-30 people,10-15,5-10,5,NaN,1
2,NaN,NaN,NaN,NaN,My role does not directly interface with the c...,2
3,50,50,50,40,30,3
4,"~15-25, with ~10 core partners",NaN,40-50,40-50,20-30,4
5,NaN,NaN,3 (I was a student in this challenge),NaN,I mainly write challenge briefs before the stu...,5
6,NaN,NaN,NaN,NaN,NaN,6
7,50 or more,15,20,25,25,7

为了以防万一我还是统一一下id列

In [82]:
df = df.reset_index(drop=True)
df["respondent_id"] = df.index

In [83]:
community_long = df[["respondent_id"] + community_cols].melt(
    id_vars="respondent_id",
    value_vars=community_cols,
    var_name="question_version",
    value_name="community_participants_number"
)
community_long

,respondent_id,question_version,community_participants_number
0,0,Approximately how many community participants ...,NaN
1,1,Approximately how many community participants ...,25-30 people
2,2,Approximately how many community participants ...,NaN
3,3,Approximately how many community participants ...,50
4,4,Approximately how many community participants ...,"~15-25, with ~10 core partners"
5,5,Approximately how many community participants ...,NaN
6,6,Approximately how many community participants ...,NaN
7,7,Approximately how many community participants ...,50 or more
8,0,Approximately how many community participants ...,NaN
9,1,Approximately how many community participants ...,10-15
10,2,Approximately how many community participants ...,NaN
11,3,Approximately how many community participants ...,50
12,4,Approximately how many community participants ...,NaN
13,5,Approximately how many community participants ...,NaN
14,6,Approximately how many community participants ...,NaN
15,7,Approximately how many community participants ...,15
16,0,Approximately how many community participants ...,100
17,1,Approximately how many community participants ...,5-10
18,2,Approximately how many community participants ...,NaN
19,3,Approximately how many community participants ...,50
20,4,Approximately how many community participants ...,40-50
21,5,Approximately how many community participants ...,3 (I was a student in this challenge)
22,6,Approximately how many community participants ...,NaN
23,7,Approximately how many community participants ...,20
24,0,Approximately how many community participants ...,50
25,1,Approximately how many community participants ...,5
26,2,Approximately how many community participants ...,NaN
27,3,Approximately how many community participants ...,40
28,4,Approximately how many community participants ...,40-50
29,5,Approximately how many community participants ...,NaN
30,6,Approximately how many community participants ...,NaN
31,7,Approximately how many community participants ...,25
32,0,Approximately how many community participants ...,75
33,1,Approximately how many community participants ...,NaN
34,2,Approximately how many community participants ...,My role does not directly interface with the c...
35,3,Approximately how many community participants ...,30
36,4,Approximately how many community participants ...,20-30
37,5,Approximately how many community participants ...,I mainly write challenge briefs before the stu...
38,6,Approximately how many community participants ...,NaN
39,7,Approximately how many community participants ...,25

In [84]:
community_long["year"] = community_long["question_version"].map(year_map)
community_long[["respondent_id", "year", "community_participants_number"]].head(5)

   respondent_id  year   community_participants_number
0              0  2021                             NaN
1              1  2021                    25-30 people
2              2  2021                             NaN
3              3  2021                              50
4              4  2021  ~15-25, with ~10 core partners

In [85]:
community_long_clean = (
    community_long
    .drop(columns=["question_version"])
    .dropna(subset=["community_participants_number"])
    .reset_index(drop=True)
)
community_long_clean.head(15)

    respondent_id          community_participants_number  year
0               1                           25-30 people  2021
1               3                                     50  2021
2               4         ~15-25, with ~10 core partners  2021
3               7                             50 or more  2021
4               1                                  10-15  2022
5               3                                     50  2022
6               7                                     15  2022
7               0                                    100  2023
8               1                                   5-10  2023
9               3                                     50  2023
10              4                                  40-50  2023
11              5  3 (I was a student in this challenge)  2023
12              7                                     20  2023
13              0                                     50  2024
14              1                                      5  2024

In [86]:
methods_base = "Which methods did you use to engage with the local stakeholders?"

methods_cols = [
    c for c in df.columns 
    if c.startswith(methods_base)
]

methods_cols

['Which methods did you use to engage with the local stakeholders?',
 'Which methods did you use to engage with the local stakeholders?.1',
 'Which methods did you use to engage with the local stakeholders?.2',
 'Which methods did you use to engage with the local stakeholders?.3',
 'Which methods did you use to engage with the local stakeholders?.4']

In [87]:
methods_year_map = {
    methods_base: 2021,
    methods_base + ".1": 2022,
    methods_base + ".2": 2023,
    methods_base + ".3": 2024,
    methods_base + ".4": 2025,
}

In [88]:
methods_wide = df[["respondent_id"] + methods_cols].copy()
methods_wide.head()

,respondent_id,Which methods did you use to engage with the local stakeholders?,Which methods did you use to engage with the local stakeholders?.1,Which methods did you use to engage with the local stakeholders?.2,Which methods did you use to engage with the local stakeholders?.3,Which methods did you use to engage with the local stakeholders?.4
0,0,NaN,NaN,"Regular meetings, Workshops, Informal discussions","Regular meetings, Informal discussions","Regular meetings, Workshops, Informal discussions"
1,1,"Regular meetings, Shared digital tools (like M...","Regular meetings, Co-design sessions, Informal...","Regular meetings, Informal discussions","Regular meetings, Co-design sessions, Informal...",NaN
2,2,NaN,NaN,NaN,NaN,NaN
3,3,Informal discussions,"Regular meetings, Informal discussions","Regular meetings, Workshops, Informal discussions","Regular meetings, Informal discussions","Regular meetings, Informal discussions"
4,4,"Regular meetings, Shared digital tools (like M...","Shared digital tools (like Miro), Workshops, I...","Regular meetings, Shared digital tools (like M...","Regular meetings, Shared digital tools (like M...","Regular meetings, Shared digital tools (like M..."

In [89]:
methods_long = methods_wide.melt(
    id_vars="respondent_id",
    value_vars=methods_cols,
    var_name="question_version",
    value_name="community_participants_methods"
)
methods_long.head(5)

,respondent_id,question_version,community_participants_methods
0,0,Which methods did you use to engage with the l...,NaN
1,1,Which methods did you use to engage with the l...,"Regular meetings, Shared digital tools (like M..."
2,2,Which methods did you use to engage with the l...,NaN
3,3,Which methods did you use to engage with the l...,Informal discussions
4,4,Which methods did you use to engage with the l...,"Regular meetings, Shared digital tools (like M..."

In [90]:
methods_long["year"] = methods_long["question_version"].map(methods_year_map)

methods_long_clean = (
    methods_long
    .drop(columns=["question_version"])
    .dropna(subset=["community_participants_methods"])
    .reset_index(drop=True)
)

methods_long_clean.head(15), methods_long_clean.shape

(    respondent_id                     community_participants_methods  year
 0               1  Regular meetings, Shared digital tools (like M...  2021
 1               3                               Informal discussions  2021
 2               4  Regular meetings, Shared digital tools (like M...  2021
 3               7                    Workshops, Informal discussions  2021
 4               1  Regular meetings, Co-design sessions, Informal...  2022
 5               3             Regular meetings, Informal discussions  2022
 6               4  Shared digital tools (like Miro), Workshops, I...  2022
 7               7  Regular meetings, Workshops, Informal discussions  2022
 8               0  Regular meetings, Workshops, Informal discussions  2023
 9               1             Regular meetings, Informal discussions  2023
 10              3  Regular meetings, Workshops, Informal discussions  2023
 11              4  Regular meetings, Shared digital tools (like M...  2023
 12              5             Regular meetings, Informal discussions  2023
 13              7  Regular meetings, Co-design sessions, Workshop...  2023
 14              0             Regular meetings, Informal discussions  2024,
 (25, 3))

In [91]:
community_panel = community_long_clean.merge(
    methods_long_clean,
    on=["respondent_id", "year"],
    how="outer"
)

community_panel.head(20)

,respondent_id,community_participants_number,year,community_participants_methods
0,0,100,2023,"Regular meetings, Workshops, Informal discussions"
1,0,50,2024,"Regular meetings, Informal discussions"
2,0,75,2025,"Regular meetings, Workshops, Informal discussions"
3,1,25-30 people,2021,"Regular meetings, Shared digital tools (like M..."
4,1,10-15,2022,"Regular meetings, Co-design sessions, Informal..."
5,1,5-10,2023,"Regular meetings, Informal discussions"
6,1,5,2024,"Regular meetings, Co-design sessions, Informal..."
7,2,My role does not directly interface with the c...,2025,NaN
8,3,50,2021,Informal discussions
9,3,50,2022,"Regular meetings, Informal discussions"
10,3,50,2023,"Regular meetings, Workshops, Informal discussions"
11,3,40,2024,"Regular meetings, Informal discussions"
12,3,30,2025,"Regular meetings, Informal discussions"
13,4,"~15-25, with ~10 core partners",2021,"Regular meetings, Shared digital tools (like M..."
14,4,NaN,2022,"Shared digital tools (like Miro), Workshops, I..."
15,4,40-50,2023,"Regular meetings, Shared digital tools (like M..."
16,4,40-50,2024,"Regular meetings, Shared digital tools (like M..."
17,4,20-30,2025,"Regular meetings, Shared digital tools (like M..."
18,5,3 (I was a student in this challenge),2023,"Regular meetings, Informal discussions"
19,5,I mainly write challenge briefs before the stu...,2025,Informal discussions

### 终于能merge了我tm累了

In [92]:
community_panel = community_panel.merge(
    analysis_df_duration_long[["respondent_id", "year", "name", "role"]],
    on=["respondent_id", "year"],
    how="left"
)

community_panel.head(20)

,respondent_id,community_participants_number,year,community_participants_methods,name,role
0,0,100,2023,"Regular meetings, Workshops, Informal discussions",Charlotte Van Voorhis,ERC program organizer
1,0,50,2024,"Regular meetings, Informal discussions",Charlotte Van Voorhis,ERC program organizer
2,0,75,2025,"Regular meetings, Workshops, Informal discussions",Charlotte Van Voorhis,ERC program organizer
3,1,25-30 people,2021,"Regular meetings, Shared digital tools (like M...",Cecil,staff/strategic advisor
4,1,10-15,2022,"Regular meetings, Co-design sessions, Informal...",Cecil,staff/strategic advisor
5,1,5-10,2023,"Regular meetings, Informal discussions",Cecil,staff/strategic advisor
6,1,5,2024,"Regular meetings, Co-design sessions, Informal...",Cecil,staff/strategic advisor
7,2,My role does not directly interface with the c...,2025,NaN,Kate Deans,ERC program organizer
8,3,50,2021,Informal discussions,Carolyn Cox,ERC program organizer
9,3,50,2022,"Regular meetings, Informal discussions",Carolyn Cox,ERC program organizer
10,3,50,2023,"Regular meetings, Workshops, Informal discussions",Carolyn Cox,ERC program organizer
11,3,40,2024,"Regular meetings, Informal discussions",Carolyn Cox,ERC program organizer
12,3,30,2025,"Regular meetings, Informal discussions",Carolyn Cox,ERC program organizer
13,4,"~15-25, with ~10 core partners",2021,"Regular meetings, Shared digital tools (like M...",Claire Martin,ERC program organizer
14,4,NaN,2022,"Shared digital tools (like Miro), Workshops, I...",Claire Martin,ERC program organizer
15,4,40-50,2023,"Regular meetings, Shared digital tools (like M...",Claire Martin,ERC program organizer
16,4,40-50,2024,"Regular meetings, Shared digital tools (like M...",Claire Martin,ERC program organizer
17,4,20-30,2025,"Regular meetings, Shared digital tools (like M...",Claire Martin,ERC program organizer
18,5,3 (I was a student in this challenge),2023,"Regular meetings, Informal discussions",Sandra Akufo,Student Participant in the 2023 New Bedford Ch...
19,5,I mainly write challenge briefs before the stu...,2025,Informal discussions,Sandra Akufo,Student Participant in the 2023 New Bedford Ch...

In [93]:
#方法使用频率分析
community_panel["community_participants_methods"].str.split(",").explode().value_counts()

community_participants_methods
 Informal discussions                22
Regular meetings                     21
 Workshops                           12
 Co-design sessions                   7
 Shared digital tools (like Miro)     5
Informal discussions                  2
Shared digital tools (like Miro)      1
Workshops                             1
Name: count, dtype: int64

In [94]:
#每年平均人数
#这有异常值咋整··

不管了先写出吧

In [95]:
analysis_df_duration_long.to_excel("staff_duration_long.xlsx", index=False)
community_panel.to_excel("community_panel.xlsx", index=False)

## Merge Advisors and Duration

In [96]:
df = df.reset_index(drop=True)
if "respondent_id" not in df.columns:
    df["respondent_id"] = df.index

In [97]:
advisor_cols = [c for c in df.columns if "advisor" in c.lower()]
advisor_cols

['Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?',
 'Which types of key advisors were most influential in shaping this challenge? Select up to three. ',
 'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.1',
 'Which types of key advisors were most influential in shaping this challenge? Select up to three. .1',
 'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.2',
 'Which types of key advisors were most influential in shaping this challenge? Select up to three. .2',
 'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.3',
 'Which types of key advisors were most influential in shaping this challenge? Select up to three. .3',
 'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.4',
 'Which types of key advisors were most influential in shaping this challenge? Select up to three. .4']

In [98]:
connectors_base = "Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?"
types_base = "Which types of key advisors were most influential in shaping this challenge? Select up to three."

In [99]:
connectors_cols = [c for c in df.columns if c.startswith(connectors_base)]
types_cols = [c for c in df.columns if c.startswith(types_base)]

connectors_cols, types_cols

(['Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?',
  'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.1',
  'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.2',
  'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.3',
  'Based on your experience, which advisors acted as connectors or bridges—either between groups within this challenge or across different challenge years?.4'],
 ['Which types of key advisors were most influential in shaping this challenge? Select up to three. ',
  'Which types of key advisors were most influential in shaping this challenge? Select up to three. .1',
  'Which types of key advisors were most influential in shaping this challenge? Select up to three. .2',
  'Which types of key advisors were most influential in shaping this challenge? Select up to three. .3',
  'Which types of key advisors were most influential in shaping this challenge? Select up to three. .4'])

In [100]:
def make_year_map(base):
    return {
        base: 2021,
        base + ".1": 2022,
        base + ".2": 2023,
        base + ".3": 2024,
        base + ".4": 2025,
    }

connectors_year_map = make_year_map(connectors_base)
types_year_map = make_year_map(types_base)

In [107]:
connectors_long = df[["respondent_id"] + connectors_cols].melt(
    id_vars="respondent_id",
    value_vars=connectors_cols,
    var_name="col",
    value_name="advisors_as_connectors"
)
connectors_long["year"] = connectors_long["col"].map(connectors_year_map)

connectors_long = (
    connectors_long
    .drop(columns="col")
    .dropna(subset=["advisors_as_connectors"])
    .reset_index(drop=True)
)

connectors_long.head(), connectors_long.shape

(   respondent_id                             advisors_as_connectors  year
 0              1                        Both connectors and bridges  2021
 1              3                           Marty Hylton, Bob Miklos  2021
 2              4  Mary Bergman, Marty Hylton, Cecil Barron Jense...  2021
 3              7                   Cecil Baron Jensen, Marty Hylton  2021
 4              3                         Bob Rulli and Teresa Crean  2022,
 (22, 3))

In [108]:
connectors_long = connectors_long.merge(
    analysis_df_id[["respondent_id", "name"]],
    on="respondent_id",
    how="left"
)
connectors_long.head()

,respondent_id,advisors_as_connectors,year,name
0,1,Both connectors and bridges,2021,Cecil
1,3,"Marty Hylton, Bob Miklos",2021,Carolyn Cox
2,4,"Mary Bergman, Marty Hylton, Cecil Barron Jense...",2021,Claire Martin
3,7,"Cecil Baron Jensen, Marty Hylton",2021,Robert Miklos FAIA
4,3,Bob Rulli and Teresa Crean,2022,Carolyn Cox

In [109]:
connectors_long.to_excel("advisors_as_connectors.xlsx", index=False)